### ISSUE TITLE
Too much data for RSA block

### ISSUE THREAD

**Issue by jmeyers91** [Q42/Qlassified-Android#13]
I'm trying to store a JWT using this package, but when I call `.put`, my app throws this error:

```
java.lang.ArrayIndexOutOfBoundsException: too much data for RSA block
        at org.spongycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineDoFinal(CipherSpi.java:461)
        at javax.crypto.Cipher.doFinal(Cipher.java:1741)
        at com.q42.qlassified.Provider.QlassifiedCrypto.encrypt(QlassifiedCrypto.java:33)
        at com.q42.qlassified.Provider.QlassifiedKeyStore.encrypt(QlassifiedKeyStore.java:177)
        at com.q42.qlassified.Provider.QlassifiedKeyStore.encryptEntry(QlassifiedKeyStore.java:119)
        at com.q42.qlassified.QlassifiedFactory.put(QlassifiedFactory.java:70)
        at com.q42.qlassified.Qlassified.put(Qlassified.java:120)
        at com.emberex.GoNote.NativeApp.storeAuthToken(NativeApp.java:143)
        at com.emberex.GoNote.NativeApp.enable(NativeApp.java:56)
        at org.apache.cordova.plugin.LocationSync.enable(LocationSync.java:63)
        at org.apache.cordova.plugin.LocationSync.execute(LocationSync.java:22)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:7)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

Is there a max-length for the values passed to `put`? Is there some way around this error?

**Comment by jmcpherson22** [comment]
Looking at QlassifiedKeyStore, It looks like the RSA keysize is either defaulting to 2048bits (OS < Marshmallow) or 512bits (OS >= Marshmallow). Depending on this RSA keysize, there is going to be a limit to how much data that you can encrypt.

**Comment by Monzonprog** [comment]
Is there any solution for it?  I´m trying to save and Uri address and I have problem with that....
