### ISSUE TITLE
Invalid permission API level 23

### ISSUE THREAD

**Issue by niqdev** [Q42/Qlassified-Android#2]
Hi,
I have the error below running the example.

It seems that adding `<uses-permission android:name="android.permission.READ_PHONE_STATE" />` to the manifest is not enough on API >= 23. [This](https://developer.android.com/training/permissions/requesting.html) should solve the issue.

My question: is this necessary?
Why should I forced to add an extra permission only to generate an alias in `QlassifiedKeyStore#getUniqueDeviceId`?
Alias are unique per app, so wouldn't be enough an alias like `qlassified`?

Thanks

``` java
java.lang.SecurityException: getDeviceId: Neither user 10065 nor current process has android.permission.READ_PHONE_STATE.
                                                                      at android.os.Parcel.readException(Parcel.java:1599)
                                                                      at android.os.Parcel.readException(Parcel.java:1552)
                                                                      at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:4175)
                                                                      at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:706)
                                                                      at com.q42.qlassified.Provider.QlassifiedKeyStore.getUniqueDeviceId(QlassifiedKeyStore.java:145)
                                                                      at com.q42.qlassified.Provider.QlassifiedKeyStore.checkKeyAvailability(QlassifiedKeyStore.java:183)
                                                                      at com.q42.qlassified.Provider.QlassifiedKeyStore.decrypt(QlassifiedKeyStore.java:221)
                                                                      at com.q42.qlassified.Provider.QlassifiedKeyStore.decryptEntry(QlassifiedKeyStore.java:161)
                                                                      at com.q42.qlassified.QlassifiedFactory.get(QlassifiedFactory.java:91)
                                                                      at com.q42.qlassified.QlassifiedFactory.getString(QlassifiedFactory.java:130)
                                                                      at com.q42.qlassified.Qlassified.getString(Qlassified.java:92)
                                                                      at com.q42.qlassified_example.MainActivity.onClick(MainActivity.java:59)
                                                                      at android.view.View.performClick(View.java:5198)
                                                                      at android.view.View$PerformClick.run(View.java:21147)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by brycehendrix** [comment]
This is a deal breaker, even if the SDK 23 permissions code is added. The permission is just too much for the perceived gain, and there are other recommended ways to get an unique ID.

Has this project been abandoned?

**Comment by ShaPOC** [comment]
First of all, sorry for the long wait. I've been busy, but am intending to continue developing this project more often in the future. I've now applied another method which with newer Android versions is just as reliable but doesn't need the permission anymore. The new method to generate the alias is included in the upcoming merge: https://github.com/Q42/Qlassified-Android/pull/6.
